# Generated by Django 5.2.1 on 2025-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_contact_status_order_coupon_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreply',
            options={'verbose_name': 'رد الإدارة', 'verbose_name_plural': 'ردود الإدارة'},
        ),
        migrations.AddIndex(
            model_name='adminreply',
            index=models.Index(fields=['contact_message', 'replied_at'], name='backend_api_contact_05084b_idx'),
        ),
    ]
