# Generated by Django 5.2.1 on 2025-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercecontactsettings',
            name='address',
            field=models.TextField(help_text='Full business address'),
        ),
    ]
